// flow-typed signature: 59c764d1dbed8b9ef693aef5308ca8ff
// flow-typed version: <<STUB>>/braintree_v^2.12.0/flow_v0.78.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'braintree'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'braintree' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'braintree/lib/braintree' {
  declare module.exports: any;
}

declare module 'braintree/lib/braintree/account_updater_daily_report' {
  declare module.exports: any;
}

declare module 'braintree/lib/braintree/ach_mandate' {
  declare module.exports: any;
}

declare module 'braintree/lib/braintree/add_on_gateway' {
  declare module.exports: any;
}

declare module 'braintree/lib/braintree/add_on' {
  declare module.exports: any;
}

declare module 'braintree/lib/braintree/address_gateway' {
  declare module.exports: any;
}

declare module 'braintree/lib/braintree/address' {
  declare module.exports: any;
}

declare module 'braintree/lib/braintree/advanced_search' {
  declare module.exports: any;
}

declare module 'braintree/lib/braintree/amex_express_checkout_card' {
  declare module.exports: any;
}

declare module 'braintree/lib/braintree/android_pay_card' {
  declare module.exports: any;
}

declare module 'braintree/lib/braintree/apple_pay_card' {
  declare module.exports: any;
}

declare module 'braintree/lib/braintree/attribute_setter' {
  declare module.exports: any;
}

declare module 'braintree/lib/braintree/authorization_adjustment' {
  declare module.exports: any;
}

declare module 'braintree/lib/braintree/braintree_gateway' {
  declare module.exports: any;
}

declare module 'braintree/lib/braintree/client_token_gateway' {
  declare module.exports: any;
}

declare module 'braintree/lib/braintree/coinbase_account_gateway' {
  declare module.exports: any;
}

declare module 'braintree/lib/braintree/coinbase_account' {
  declare module.exports: any;
}

declare module 'braintree/lib/braintree/config' {
  declare module.exports: any;
}

declare module 'braintree/lib/braintree/connected_merchant_paypal_status_changed' {
  declare module.exports: any;
}

declare module 'braintree/lib/braintree/connected_merchant_status_transitioned' {
  declare module.exports: any;
}

declare module 'braintree/lib/braintree/credentials_parser' {
  declare module.exports: any;
}

declare module 'braintree/lib/braintree/credit_card_gateway' {
  declare module.exports: any;
}

declare module 'braintree/lib/braintree/credit_card_verification_gateway' {
  declare module.exports: any;
}

declare module 'braintree/lib/braintree/credit_card_verification_search' {
  declare module.exports: any;
}

declare module 'braintree/lib/braintree/credit_card_verification' {
  declare module.exports: any;
}

declare module 'braintree/lib/braintree/credit_card' {
  declare module.exports: any;
}

declare module 'braintree/lib/braintree/customer_gateway' {
  declare module.exports: any;
}

declare module 'braintree/lib/braintree/customer_search' {
  declare module.exports: any;
}

declare module 'braintree/lib/braintree/customer' {
  declare module.exports: any;
}

declare module 'braintree/lib/braintree/digest' {
  declare module.exports: any;
}

declare module 'braintree/lib/braintree/disbursement_details' {
  declare module.exports: any;
}

declare module 'braintree/lib/braintree/disbursement_gateway' {
  declare module.exports: any;
}

declare module 'braintree/lib/braintree/disbursement' {
  declare module.exports: any;
}

declare module 'braintree/lib/braintree/discount_gateway' {
  declare module.exports: any;
}

declare module 'braintree/lib/braintree/discount' {
  declare module.exports: any;
}

declare module 'braintree/lib/braintree/dispute_gateway' {
  declare module.exports: any;
}

declare module 'braintree/lib/braintree/dispute_search' {
  declare module.exports: any;
}

declare module 'braintree/lib/braintree/dispute' {
  declare module.exports: any;
}

declare module 'braintree/lib/braintree/document_upload_gateway' {
  declare module.exports: any;
}

declare module 'braintree/lib/braintree/document_upload' {
  declare module.exports: any;
}

declare module 'braintree/lib/braintree/environment' {
  declare module.exports: any;
}

declare module 'braintree/lib/braintree/error_response' {
  declare module.exports: any;
}

declare module 'braintree/lib/braintree/error_types' {
  declare module.exports: any;
}

declare module 'braintree/lib/braintree/exceptions' {
  declare module.exports: any;
}

declare module 'braintree/lib/braintree/facilitated_details' {
  declare module.exports: any;
}

declare module 'braintree/lib/braintree/facilitator_details' {
  declare module.exports: any;
}

declare module 'braintree/lib/braintree/gateway' {
  declare module.exports: any;
}

declare module 'braintree/lib/braintree/granted_payment_instrument_update' {
  declare module.exports: any;
}

declare module 'braintree/lib/braintree/http' {
  declare module.exports: any;
}

declare module 'braintree/lib/braintree/ideal_payment_gateway' {
  declare module.exports: any;
}

declare module 'braintree/lib/braintree/ideal_payment' {
  declare module.exports: any;
}

declare module 'braintree/lib/braintree/masterpass_card' {
  declare module.exports: any;
}

declare module 'braintree/lib/braintree/merchant_account_gateway' {
  declare module.exports: any;
}

declare module 'braintree/lib/braintree/merchant_account' {
  declare module.exports: any;
}

declare module 'braintree/lib/braintree/merchant_gateway' {
  declare module.exports: any;
}

declare module 'braintree/lib/braintree/merchant' {
  declare module.exports: any;
}

declare module 'braintree/lib/braintree/oauth_access_revocation' {
  declare module.exports: any;
}

declare module 'braintree/lib/braintree/oauth_credentials' {
  declare module.exports: any;
}

declare module 'braintree/lib/braintree/oauth_gateway' {
  declare module.exports: any;
}

declare module 'braintree/lib/braintree/paginated_response_stream' {
  declare module.exports: any;
}

declare module 'braintree/lib/braintree/paginated_response' {
  declare module.exports: any;
}

declare module 'braintree/lib/braintree/partner_merchant' {
  declare module.exports: any;
}

declare module 'braintree/lib/braintree/payment_instrument_types' {
  declare module.exports: any;
}

declare module 'braintree/lib/braintree/payment_method_gateway' {
  declare module.exports: any;
}

declare module 'braintree/lib/braintree/payment_method_nonce_gateway' {
  declare module.exports: any;
}

declare module 'braintree/lib/braintree/payment_method_nonce' {
  declare module.exports: any;
}

declare module 'braintree/lib/braintree/paypal_account_gateway' {
  declare module.exports: any;
}

declare module 'braintree/lib/braintree/paypal_account' {
  declare module.exports: any;
}

declare module 'braintree/lib/braintree/plan_gateway' {
  declare module.exports: any;
}

declare module 'braintree/lib/braintree/plan' {
  declare module.exports: any;
}

declare module 'braintree/lib/braintree/risk_data' {
  declare module.exports: any;
}

declare module 'braintree/lib/braintree/samsung_pay_card' {
  declare module.exports: any;
}

declare module 'braintree/lib/braintree/search_response_stream' {
  declare module.exports: any;
}

declare module 'braintree/lib/braintree/search_response' {
  declare module.exports: any;
}

declare module 'braintree/lib/braintree/settlement_batch_summary_gateway' {
  declare module.exports: any;
}

declare module 'braintree/lib/braintree/settlement_batch_summary' {
  declare module.exports: any;
}

declare module 'braintree/lib/braintree/signature_service' {
  declare module.exports: any;
}

declare module 'braintree/lib/braintree/subscription_gateway' {
  declare module.exports: any;
}

declare module 'braintree/lib/braintree/subscription_search' {
  declare module.exports: any;
}

declare module 'braintree/lib/braintree/subscription' {
  declare module.exports: any;
}

declare module 'braintree/lib/braintree/test/credit_card_defaults' {
  declare module.exports: any;
}

declare module 'braintree/lib/braintree/test/credit_card_numbers' {
  declare module.exports: any;
}

declare module 'braintree/lib/braintree/test/merchant_account' {
  declare module.exports: any;
}

declare module 'braintree/lib/braintree/test/nonces' {
  declare module.exports: any;
}

declare module 'braintree/lib/braintree/test/transaction_amounts' {
  declare module.exports: any;
}

declare module 'braintree/lib/braintree/test/venmo_sdk' {
  declare module.exports: any;
}

declare module 'braintree/lib/braintree/testing_gateway' {
  declare module.exports: any;
}

declare module 'braintree/lib/braintree/three_d_secure_info' {
  declare module.exports: any;
}

declare module 'braintree/lib/braintree/transaction_details' {
  declare module.exports: any;
}

declare module 'braintree/lib/braintree/transaction_gateway' {
  declare module.exports: any;
}

declare module 'braintree/lib/braintree/transaction_line_item_gateway' {
  declare module.exports: any;
}

declare module 'braintree/lib/braintree/transaction_line_item' {
  declare module.exports: any;
}

declare module 'braintree/lib/braintree/transaction_search' {
  declare module.exports: any;
}

declare module 'braintree/lib/braintree/transaction' {
  declare module.exports: any;
}

declare module 'braintree/lib/braintree/transparent_redirect_gateway' {
  declare module.exports: any;
}

declare module 'braintree/lib/braintree/unknown_payment_method' {
  declare module.exports: any;
}

declare module 'braintree/lib/braintree/us_bank_account_gateway' {
  declare module.exports: any;
}

declare module 'braintree/lib/braintree/us_bank_account_verification_gateway' {
  declare module.exports: any;
}

declare module 'braintree/lib/braintree/us_bank_account_verification_search' {
  declare module.exports: any;
}

declare module 'braintree/lib/braintree/us_bank_account_verification' {
  declare module.exports: any;
}

declare module 'braintree/lib/braintree/us_bank_account' {
  declare module.exports: any;
}

declare module 'braintree/lib/braintree/util' {
  declare module.exports: any;
}

declare module 'braintree/lib/braintree/validation_error_codes' {
  declare module.exports: any;
}

declare module 'braintree/lib/braintree/validation_error' {
  declare module.exports: any;
}

declare module 'braintree/lib/braintree/validation_errors_collection' {
  declare module.exports: any;
}

declare module 'braintree/lib/braintree/venmo_account' {
  declare module.exports: any;
}

declare module 'braintree/lib/braintree/visa_checkout_card' {
  declare module.exports: any;
}

declare module 'braintree/lib/braintree/webhook_notification_gateway' {
  declare module.exports: any;
}

declare module 'braintree/lib/braintree/webhook_notification' {
  declare module.exports: any;
}

declare module 'braintree/lib/braintree/webhook_testing_gateway' {
  declare module.exports: any;
}

declare module 'braintree/vendor/querystring.node.js.511d6a2/querystring-parse' {
  declare module.exports: any;
}

declare module 'braintree/vendor/querystring.node.js.511d6a2/querystring-stringify' {
  declare module.exports: any;
}

declare module 'braintree/vendor/querystring.node.js.511d6a2/querystring' {
  declare module.exports: any;
}

declare module 'braintree/vendor/querystring.node.js.511d6a2/test' {
  declare module.exports: any;
}

declare module 'braintree/vendor/querystring.node.js.511d6a2/util' {
  declare module.exports: any;
}

// Filename aliases
declare module 'braintree/index' {
  declare module.exports: $Exports<'braintree'>;
}
declare module 'braintree/index.js' {
  declare module.exports: $Exports<'braintree'>;
}
declare module 'braintree/lib/braintree.js' {
  declare module.exports: $Exports<'braintree/lib/braintree'>;
}
declare module 'braintree/lib/braintree/account_updater_daily_report.js' {
  declare module.exports: $Exports<'braintree/lib/braintree/account_updater_daily_report'>;
}
declare module 'braintree/lib/braintree/ach_mandate.js' {
  declare module.exports: $Exports<'braintree/lib/braintree/ach_mandate'>;
}
declare module 'braintree/lib/braintree/add_on_gateway.js' {
  declare module.exports: $Exports<'braintree/lib/braintree/add_on_gateway'>;
}
declare module 'braintree/lib/braintree/add_on.js' {
  declare module.exports: $Exports<'braintree/lib/braintree/add_on'>;
}
declare module 'braintree/lib/braintree/address_gateway.js' {
  declare module.exports: $Exports<'braintree/lib/braintree/address_gateway'>;
}
declare module 'braintree/lib/braintree/address.js' {
  declare module.exports: $Exports<'braintree/lib/braintree/address'>;
}
declare module 'braintree/lib/braintree/advanced_search.js' {
  declare module.exports: $Exports<'braintree/lib/braintree/advanced_search'>;
}
declare module 'braintree/lib/braintree/amex_express_checkout_card.js' {
  declare module.exports: $Exports<'braintree/lib/braintree/amex_express_checkout_card'>;
}
declare module 'braintree/lib/braintree/android_pay_card.js' {
  declare module.exports: $Exports<'braintree/lib/braintree/android_pay_card'>;
}
declare module 'braintree/lib/braintree/apple_pay_card.js' {
  declare module.exports: $Exports<'braintree/lib/braintree/apple_pay_card'>;
}
declare module 'braintree/lib/braintree/attribute_setter.js' {
  declare module.exports: $Exports<'braintree/lib/braintree/attribute_setter'>;
}
declare module 'braintree/lib/braintree/authorization_adjustment.js' {
  declare module.exports: $Exports<'braintree/lib/braintree/authorization_adjustment'>;
}
declare module 'braintree/lib/braintree/braintree_gateway.js' {
  declare module.exports: $Exports<'braintree/lib/braintree/braintree_gateway'>;
}
declare module 'braintree/lib/braintree/client_token_gateway.js' {
  declare module.exports: $Exports<'braintree/lib/braintree/client_token_gateway'>;
}
declare module 'braintree/lib/braintree/coinbase_account_gateway.js' {
  declare module.exports: $Exports<'braintree/lib/braintree/coinbase_account_gateway'>;
}
declare module 'braintree/lib/braintree/coinbase_account.js' {
  declare module.exports: $Exports<'braintree/lib/braintree/coinbase_account'>;
}
declare module 'braintree/lib/braintree/config.js' {
  declare module.exports: $Exports<'braintree/lib/braintree/config'>;
}
declare module 'braintree/lib/braintree/connected_merchant_paypal_status_changed.js' {
  declare module.exports: $Exports<'braintree/lib/braintree/connected_merchant_paypal_status_changed'>;
}
declare module 'braintree/lib/braintree/connected_merchant_status_transitioned.js' {
  declare module.exports: $Exports<'braintree/lib/braintree/connected_merchant_status_transitioned'>;
}
declare module 'braintree/lib/braintree/credentials_parser.js' {
  declare module.exports: $Exports<'braintree/lib/braintree/credentials_parser'>;
}
declare module 'braintree/lib/braintree/credit_card_gateway.js' {
  declare module.exports: $Exports<'braintree/lib/braintree/credit_card_gateway'>;
}
declare module 'braintree/lib/braintree/credit_card_verification_gateway.js' {
  declare module.exports: $Exports<'braintree/lib/braintree/credit_card_verification_gateway'>;
}
declare module 'braintree/lib/braintree/credit_card_verification_search.js' {
  declare module.exports: $Exports<'braintree/lib/braintree/credit_card_verification_search'>;
}
declare module 'braintree/lib/braintree/credit_card_verification.js' {
  declare module.exports: $Exports<'braintree/lib/braintree/credit_card_verification'>;
}
declare module 'braintree/lib/braintree/credit_card.js' {
  declare module.exports: $Exports<'braintree/lib/braintree/credit_card'>;
}
declare module 'braintree/lib/braintree/customer_gateway.js' {
  declare module.exports: $Exports<'braintree/lib/braintree/customer_gateway'>;
}
declare module 'braintree/lib/braintree/customer_search.js' {
  declare module.exports: $Exports<'braintree/lib/braintree/customer_search'>;
}
declare module 'braintree/lib/braintree/customer.js' {
  declare module.exports: $Exports<'braintree/lib/braintree/customer'>;
}
declare module 'braintree/lib/braintree/digest.js' {
  declare module.exports: $Exports<'braintree/lib/braintree/digest'>;
}
declare module 'braintree/lib/braintree/disbursement_details.js' {
  declare module.exports: $Exports<'braintree/lib/braintree/disbursement_details'>;
}
declare module 'braintree/lib/braintree/disbursement_gateway.js' {
  declare module.exports: $Exports<'braintree/lib/braintree/disbursement_gateway'>;
}
declare module 'braintree/lib/braintree/disbursement.js' {
  declare module.exports: $Exports<'braintree/lib/braintree/disbursement'>;
}
declare module 'braintree/lib/braintree/discount_gateway.js' {
  declare module.exports: $Exports<'braintree/lib/braintree/discount_gateway'>;
}
declare module 'braintree/lib/braintree/discount.js' {
  declare module.exports: $Exports<'braintree/lib/braintree/discount'>;
}
declare module 'braintree/lib/braintree/dispute_gateway.js' {
  declare module.exports: $Exports<'braintree/lib/braintree/dispute_gateway'>;
}
declare module 'braintree/lib/braintree/dispute_search.js' {
  declare module.exports: $Exports<'braintree/lib/braintree/dispute_search'>;
}
declare module 'braintree/lib/braintree/dispute.js' {
  declare module.exports: $Exports<'braintree/lib/braintree/dispute'>;
}
declare module 'braintree/lib/braintree/document_upload_gateway.js' {
  declare module.exports: $Exports<'braintree/lib/braintree/document_upload_gateway'>;
}
declare module 'braintree/lib/braintree/document_upload.js' {
  declare module.exports: $Exports<'braintree/lib/braintree/document_upload'>;
}
declare module 'braintree/lib/braintree/environment.js' {
  declare module.exports: $Exports<'braintree/lib/braintree/environment'>;
}
declare module 'braintree/lib/braintree/error_response.js' {
  declare module.exports: $Exports<'braintree/lib/braintree/error_response'>;
}
declare module 'braintree/lib/braintree/error_types.js' {
  declare module.exports: $Exports<'braintree/lib/braintree/error_types'>;
}
declare module 'braintree/lib/braintree/exceptions.js' {
  declare module.exports: $Exports<'braintree/lib/braintree/exceptions'>;
}
declare module 'braintree/lib/braintree/facilitated_details.js' {
  declare module.exports: $Exports<'braintree/lib/braintree/facilitated_details'>;
}
declare module 'braintree/lib/braintree/facilitator_details.js' {
  declare module.exports: $Exports<'braintree/lib/braintree/facilitator_details'>;
}
declare module 'braintree/lib/braintree/gateway.js' {
  declare module.exports: $Exports<'braintree/lib/braintree/gateway'>;
}
declare module 'braintree/lib/braintree/granted_payment_instrument_update.js' {
  declare module.exports: $Exports<'braintree/lib/braintree/granted_payment_instrument_update'>;
}
declare module 'braintree/lib/braintree/http.js' {
  declare module.exports: $Exports<'braintree/lib/braintree/http'>;
}
declare module 'braintree/lib/braintree/ideal_payment_gateway.js' {
  declare module.exports: $Exports<'braintree/lib/braintree/ideal_payment_gateway'>;
}
declare module 'braintree/lib/braintree/ideal_payment.js' {
  declare module.exports: $Exports<'braintree/lib/braintree/ideal_payment'>;
}
declare module 'braintree/lib/braintree/masterpass_card.js' {
  declare module.exports: $Exports<'braintree/lib/braintree/masterpass_card'>;
}
declare module 'braintree/lib/braintree/merchant_account_gateway.js' {
  declare module.exports: $Exports<'braintree/lib/braintree/merchant_account_gateway'>;
}
declare module 'braintree/lib/braintree/merchant_account.js' {
  declare module.exports: $Exports<'braintree/lib/braintree/merchant_account'>;
}
declare module 'braintree/lib/braintree/merchant_gateway.js' {
  declare module.exports: $Exports<'braintree/lib/braintree/merchant_gateway'>;
}
declare module 'braintree/lib/braintree/merchant.js' {
  declare module.exports: $Exports<'braintree/lib/braintree/merchant'>;
}
declare module 'braintree/lib/braintree/oauth_access_revocation.js' {
  declare module.exports: $Exports<'braintree/lib/braintree/oauth_access_revocation'>;
}
declare module 'braintree/lib/braintree/oauth_credentials.js' {
  declare module.exports: $Exports<'braintree/lib/braintree/oauth_credentials'>;
}
declare module 'braintree/lib/braintree/oauth_gateway.js' {
  declare module.exports: $Exports<'braintree/lib/braintree/oauth_gateway'>;
}
declare module 'braintree/lib/braintree/paginated_response_stream.js' {
  declare module.exports: $Exports<'braintree/lib/braintree/paginated_response_stream'>;
}
declare module 'braintree/lib/braintree/paginated_response.js' {
  declare module.exports: $Exports<'braintree/lib/braintree/paginated_response'>;
}
declare module 'braintree/lib/braintree/partner_merchant.js' {
  declare module.exports: $Exports<'braintree/lib/braintree/partner_merchant'>;
}
declare module 'braintree/lib/braintree/payment_instrument_types.js' {
  declare module.exports: $Exports<'braintree/lib/braintree/payment_instrument_types'>;
}
declare module 'braintree/lib/braintree/payment_method_gateway.js' {
  declare module.exports: $Exports<'braintree/lib/braintree/payment_method_gateway'>;
}
declare module 'braintree/lib/braintree/payment_method_nonce_gateway.js' {
  declare module.exports: $Exports<'braintree/lib/braintree/payment_method_nonce_gateway'>;
}
declare module 'braintree/lib/braintree/payment_method_nonce.js' {
  declare module.exports: $Exports<'braintree/lib/braintree/payment_method_nonce'>;
}
declare module 'braintree/lib/braintree/paypal_account_gateway.js' {
  declare module.exports: $Exports<'braintree/lib/braintree/paypal_account_gateway'>;
}
declare module 'braintree/lib/braintree/paypal_account.js' {
  declare module.exports: $Exports<'braintree/lib/braintree/paypal_account'>;
}
declare module 'braintree/lib/braintree/plan_gateway.js' {
  declare module.exports: $Exports<'braintree/lib/braintree/plan_gateway'>;
}
declare module 'braintree/lib/braintree/plan.js' {
  declare module.exports: $Exports<'braintree/lib/braintree/plan'>;
}
declare module 'braintree/lib/braintree/risk_data.js' {
  declare module.exports: $Exports<'braintree/lib/braintree/risk_data'>;
}
declare module 'braintree/lib/braintree/samsung_pay_card.js' {
  declare module.exports: $Exports<'braintree/lib/braintree/samsung_pay_card'>;
}
declare module 'braintree/lib/braintree/search_response_stream.js' {
  declare module.exports: $Exports<'braintree/lib/braintree/search_response_stream'>;
}
declare module 'braintree/lib/braintree/search_response.js' {
  declare module.exports: $Exports<'braintree/lib/braintree/search_response'>;
}
declare module 'braintree/lib/braintree/settlement_batch_summary_gateway.js' {
  declare module.exports: $Exports<'braintree/lib/braintree/settlement_batch_summary_gateway'>;
}
declare module 'braintree/lib/braintree/settlement_batch_summary.js' {
  declare module.exports: $Exports<'braintree/lib/braintree/settlement_batch_summary'>;
}
declare module 'braintree/lib/braintree/signature_service.js' {
  declare module.exports: $Exports<'braintree/lib/braintree/signature_service'>;
}
declare module 'braintree/lib/braintree/subscription_gateway.js' {
  declare module.exports: $Exports<'braintree/lib/braintree/subscription_gateway'>;
}
declare module 'braintree/lib/braintree/subscription_search.js' {
  declare module.exports: $Exports<'braintree/lib/braintree/subscription_search'>;
}
declare module 'braintree/lib/braintree/subscription.js' {
  declare module.exports: $Exports<'braintree/lib/braintree/subscription'>;
}
declare module 'braintree/lib/braintree/test/credit_card_defaults.js' {
  declare module.exports: $Exports<'braintree/lib/braintree/test/credit_card_defaults'>;
}
declare module 'braintree/lib/braintree/test/credit_card_numbers.js' {
  declare module.exports: $Exports<'braintree/lib/braintree/test/credit_card_numbers'>;
}
declare module 'braintree/lib/braintree/test/merchant_account.js' {
  declare module.exports: $Exports<'braintree/lib/braintree/test/merchant_account'>;
}
declare module 'braintree/lib/braintree/test/nonces.js' {
  declare module.exports: $Exports<'braintree/lib/braintree/test/nonces'>;
}
declare module 'braintree/lib/braintree/test/transaction_amounts.js' {
  declare module.exports: $Exports<'braintree/lib/braintree/test/transaction_amounts'>;
}
declare module 'braintree/lib/braintree/test/venmo_sdk.js' {
  declare module.exports: $Exports<'braintree/lib/braintree/test/venmo_sdk'>;
}
declare module 'braintree/lib/braintree/testing_gateway.js' {
  declare module.exports: $Exports<'braintree/lib/braintree/testing_gateway'>;
}
declare module 'braintree/lib/braintree/three_d_secure_info.js' {
  declare module.exports: $Exports<'braintree/lib/braintree/three_d_secure_info'>;
}
declare module 'braintree/lib/braintree/transaction_details.js' {
  declare module.exports: $Exports<'braintree/lib/braintree/transaction_details'>;
}
declare module 'braintree/lib/braintree/transaction_gateway.js' {
  declare module.exports: $Exports<'braintree/lib/braintree/transaction_gateway'>;
}
declare module 'braintree/lib/braintree/transaction_line_item_gateway.js' {
  declare module.exports: $Exports<'braintree/lib/braintree/transaction_line_item_gateway'>;
}
declare module 'braintree/lib/braintree/transaction_line_item.js' {
  declare module.exports: $Exports<'braintree/lib/braintree/transaction_line_item'>;
}
declare module 'braintree/lib/braintree/transaction_search.js' {
  declare module.exports: $Exports<'braintree/lib/braintree/transaction_search'>;
}
declare module 'braintree/lib/braintree/transaction.js' {
  declare module.exports: $Exports<'braintree/lib/braintree/transaction'>;
}
declare module 'braintree/lib/braintree/transparent_redirect_gateway.js' {
  declare module.exports: $Exports<'braintree/lib/braintree/transparent_redirect_gateway'>;
}
declare module 'braintree/lib/braintree/unknown_payment_method.js' {
  declare module.exports: $Exports<'braintree/lib/braintree/unknown_payment_method'>;
}
declare module 'braintree/lib/braintree/us_bank_account_gateway.js' {
  declare module.exports: $Exports<'braintree/lib/braintree/us_bank_account_gateway'>;
}
declare module 'braintree/lib/braintree/us_bank_account_verification_gateway.js' {
  declare module.exports: $Exports<'braintree/lib/braintree/us_bank_account_verification_gateway'>;
}
declare module 'braintree/lib/braintree/us_bank_account_verification_search.js' {
  declare module.exports: $Exports<'braintree/lib/braintree/us_bank_account_verification_search'>;
}
declare module 'braintree/lib/braintree/us_bank_account_verification.js' {
  declare module.exports: $Exports<'braintree/lib/braintree/us_bank_account_verification'>;
}
declare module 'braintree/lib/braintree/us_bank_account.js' {
  declare module.exports: $Exports<'braintree/lib/braintree/us_bank_account'>;
}
declare module 'braintree/lib/braintree/util.js' {
  declare module.exports: $Exports<'braintree/lib/braintree/util'>;
}
declare module 'braintree/lib/braintree/validation_error_codes.js' {
  declare module.exports: $Exports<'braintree/lib/braintree/validation_error_codes'>;
}
declare module 'braintree/lib/braintree/validation_error.js' {
  declare module.exports: $Exports<'braintree/lib/braintree/validation_error'>;
}
declare module 'braintree/lib/braintree/validation_errors_collection.js' {
  declare module.exports: $Exports<'braintree/lib/braintree/validation_errors_collection'>;
}
declare module 'braintree/lib/braintree/venmo_account.js' {
  declare module.exports: $Exports<'braintree/lib/braintree/venmo_account'>;
}
declare module 'braintree/lib/braintree/visa_checkout_card.js' {
  declare module.exports: $Exports<'braintree/lib/braintree/visa_checkout_card'>;
}
declare module 'braintree/lib/braintree/webhook_notification_gateway.js' {
  declare module.exports: $Exports<'braintree/lib/braintree/webhook_notification_gateway'>;
}
declare module 'braintree/lib/braintree/webhook_notification.js' {
  declare module.exports: $Exports<'braintree/lib/braintree/webhook_notification'>;
}
declare module 'braintree/lib/braintree/webhook_testing_gateway.js' {
  declare module.exports: $Exports<'braintree/lib/braintree/webhook_testing_gateway'>;
}
declare module 'braintree/vendor/querystring.node.js.511d6a2/querystring-parse.js' {
  declare module.exports: $Exports<'braintree/vendor/querystring.node.js.511d6a2/querystring-parse'>;
}
declare module 'braintree/vendor/querystring.node.js.511d6a2/querystring-stringify.js' {
  declare module.exports: $Exports<'braintree/vendor/querystring.node.js.511d6a2/querystring-stringify'>;
}
declare module 'braintree/vendor/querystring.node.js.511d6a2/querystring.js' {
  declare module.exports: $Exports<'braintree/vendor/querystring.node.js.511d6a2/querystring'>;
}
declare module 'braintree/vendor/querystring.node.js.511d6a2/test.js' {
  declare module.exports: $Exports<'braintree/vendor/querystring.node.js.511d6a2/test'>;
}
declare module 'braintree/vendor/querystring.node.js.511d6a2/util.js' {
  declare module.exports: $Exports<'braintree/vendor/querystring.node.js.511d6a2/util'>;
}
